### ISSUE TITLE
typo in npm readme

### ISSUE THREAD

**Issue by zvikarp** [sdnetwork/winston3-azureblob-transport#1]
hi, this package saved me, thanks!

wanted to point out that the readme on the npm site is not updated.

instead of:
```
  var winston = require("winston");
  var azureBlobTransport = require("winston-azureblob-transport");
``` 

it should be (with the "3"):
```
  var winston = require("winston");
  var azureBlobTransport = require("winston3-azureblob-transport");
```

i see that you have fixed this here but it is not updated on npm and can cause confusion.

**Comment by sdnetwork** [comment]
thx @zvikarp, it's fixed now
